### ISSUE TITLE
Can this be a sub-project of team API for the dashboard?

### ISSUE THREAD

**Issue by wslack** [18F/about_yml#3]
Hi @mbland,

The dashboard, by virtue of capitalization, has this at the top of the list, but I'm not sure the current description is accessible. I'm also not sure that this repo is its own "project" in the way that other things on the dashboard are.

Since it's part of the Team API effort, what do you think about defining it as a child repo of that project?

**Comment by mbland** [comment]
Yeah, I like that suggestion. I've also thought it would maybe make sense to have a new project `type`s such as `library` or `infrastructure`, since this project was not only a child of Team API, but a reusable component.

Thoughts? (This also means it's time to prioritize linking child repos to parents.)

**Comment by wslack** [comment]
Maybe just "reusable?" I think that will be interesting to lots of people, but not most of the dashboard visitors. Just a guess though.

**Comment by mbland** [comment]
Discussing more generally in #4.

**Comment by mtorres253** [comment]
Will discuss this on 11/3 in meeting about schema update

**Comment by mbland** [comment]
Also subsumed by #15.

**Comment by wslack** [comment]
:+1:
