### ISSUE TITLE
Improve help text in the about_yml_generate file

### ISSUE THREAD

**Issue by mbland** [18F/about_yml#39]
@gboone just shared this set of questions form @melodykramer; I'm thinking these could become the new `.about.yml` descriptions in the schema, to make the generated template files (via `about_yml_generate`) easier to fill out:

How would you describe your project to someone at a dinner party? (3-5 lines)
How should people contact your project? Who is the main point of contact?
Are there any blog posts or media that should be linked?
How would you describe the impact of your project?
What problem is your project trying to solve?
What is the solution your project puts forth?
What is the goal of your project?
Who are the partners on your project?
What are the key links associated with your project?
What are the key milestones you’ve achieved recently?
Who is on the team?
How could your project be adapted by another agency, local, or state gov’t?
How would you describe the current progress of your project?

**Comment by mtorres253** [comment]
| full_name | What is the full name of your project? |

**Comment by mtorres253** [comment]
# What is the url slug you want to use for your project? (required)
name:

# What is the full name of your project? (required)
full_name:

# How would you describe your project to someone at a dinner party? (3-5 lines, required)
description:

# What kind of content is contained in the project repository?
# values: app, docs, policy
type:

# What kind of team owns the repository? (required)
# values: guild, working-group, project
owner_type:

# Name of the main project repo if this is a sub-repo; name of the working group/guild repo if this is a working group/guild subproject
parent:

# How would you describe the current stage of your project? (required)
# values: discovery, alpha, beta, live
stage:

# Description of the project
description:

# Tags that describe the project or aspects of the project
tags:
- 

# Should this repo have automated tests? If so, set to `true`. (required)
# values: true, false
testable:

# Which 18F team members are on your team or otherwise contributing to the project? For each team member, specify their github name, id and role. (required)
# Items:
# - github: GitHub user name
#   id: Internal team identifier/user name
#   role: Team member's role; leads should be designated as 'lead'
team:
- 

# Who are the partners on your project?
partners:
- 

# Organizations or individuals who have adopted the project for their own use
# Items:
# - id: The name of the organization or individual
#   url: A URL to the user's version of the project
users:
- 

# What are the key milestones you've achieved recently?
# Example: - "July 2015: Discovery completed"
milestones:
- 

# What technologies are used in this project?
stack:
- 

# How would you describe the long term impact of your project, and shorter term metrics (e.g. number of users in the next year or money saved)?
impact:

# What are the services used to supply project status information?
# Items:
# - name: Name of the service
#   category: Type of the service
#   url: URL for detailed information
#   badge: URL for the status badge
services:
- 

# What are the licences that apply to the project and/or its components? (required)
# Items by property name pattern:
#   .*:
#     name: Name of the license from the Software Package Data Exchange (SPDX): https://spdx.org/licenses/
#     url: URL for the text of the license
licenses:
  placeholder_label:

# What is the tag used to locate 18F blog posts about your project? 
# choose one tag from the ones listed here: https://18f.gsa.gov/tags/
blog:
- 

# What are the key links associated with your project?
# Items:
# - url: URL for the link
#   text: Anchor text for the link
links:
- 

# How should people contact your project? Who is the main point of contact?
# Items:
# - url: URL for the link
#   text: Anchor text for the link
contact:
- 

# What other organizations or individuals have adopted the project for their own use?
users:

**Comment by mtorres253** [comment]
Here is a sample of the file that we want to be generated
[generated.about.yml.txt](https://github.com/18F/about_yml/files/63628/generated.about.yml.txt)

Cross reference #59

**Comment by mtorres253** [comment]
This is done. Just updated the about_yml gem and re-ran the about_yml_generate command
