### ISSUE TITLE
Determine process for pull requests

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#41]
Per retro, we need to come up with a process on handling pull requests. @ccostino will work with the devs to come up with the process

**Comment by ccostino** [comment]
Here are the notes so far I have from our meeting yesterday:
- Rotating review schedule so someone is always on the hook or call out folks specifically if you’re in need of a review (which a couple of folks currently do)?  Didn’t quite come to consensus on this.
- Only use “Connects #xx” for referencing issues in GitHub so Waffle picks up on it but does not automatically move people’s cheese; need to look into this further.
- Smaller issues that are paired on do not need formal separate code reviews, however one caveat (see next bullet).
- Large issues/bits of work should be reviewed by one other person, even if paired on.
- People other than yourself press the merge button.
- Work in branches on repo directly if internal to 18F; fork if external.

**Comment by ccostino** [comment]
Documentation for using Waffle is found here:  https://github.com/waffleio/waffle.io/wiki/FAQs

I am reviewing this to address the second bullet point and see if it's easier to make use of the automatic hooks after talking briefly with @mbland yesterday about it.

**Comment by ccostino** [comment]
I am also working through this guide that is Waffle's recommended workflow:  https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking

**Comment by ccostino** [comment]
One thing I have been thinking about and that this workflow guide highlights is having a separate column for something that needs review.  Given that we still need to agree on whether or not we are just going to ping each other or setup a rotation of sorts for someone to be on point each week, perhaps having an explicit column in place on the Waffle board will help in noting which issues that have work associated with them that require a review.

Let's discuss this during the sprint planning meeting if we have a moment.

**Comment by jessieay** [comment]
This documents C2's process: https://github.com/18F/C2/blob/master/doc/team_practices.md

One thing I do not like about it is the requirement to QA before merging -- my feeling is that if you are writing good tests you should not need to QA before merging. And if QA happens after merge, it doesn't block stories from getting through. But other than that, the process seems to be working for a team of 5 devs

**Comment by ccostino** [comment]
Awesome!  This is a great source of help for us, thanks @jessieay!

Regarding the QA before merging, I have a slightly different viewpoint on it.  First and foremost, I agree that you should have good tests and it shouldn't be left strictly up to manual QA after the fact (especially after already merging), that is just asking for trouble and living in a world of pain and suffering.  I've been there previously and have absolutely no desire to go back!

That said, I think that when you're the person writing the code and the tests it is highly likely that you are still going to miss something due to confirmation bias; this is true even while pairing, though the chances are greatly reduced especially if the participants are trained and comfortable in questioning everything.  Having someone else actually make use of the change(s) (not just reading through the code) and validate that the behaviors/assumptions/intentions/outcomes of the change(s) are in parity with what is actually expected is absolutely valuable and often-times brings to light several issues that were not accounted for, either with the change itself or the purpose behind the change.  Perhaps the story wasn't as useful as previously thought or it missed a critical component of user feedback.

I'm in complete agreement that QA after merging is a pointless exercise since it doesn't block Bad Things(TM) from happening (though definitely still better than nothing!), but I think that QA before merging as a final checkpoint after a formal code review is a valuable exercise and often times a great learning experience for everyone who is involved with the work.  When and how this should all work in the development process is certainly up for debate and dependent on a team's and project's needs, but I think it would be worth having a broader discussion about all of this!

**Comment by mbland** [comment]
Whoa, we have dedicated QA testers? Or is that a C2 thing that GSA or someone else is managing or paying for?

For our purposes, I wouldn't anticipate the need to reference QA specifically. (But if we _had_ dedicated testers who fit into the workflow and provided acceleration rather than drag when it came to high-level features, that would be cool.)

**Comment by ccostino** [comment]
I was just talking about this with @micahsaul yesterday while reviewing our code review interviews and there's no formal testing role at 18F; now that you mention it I am curious about this too, are there actual testers on C2 or is this just a formal step that someone on the team will fill in for when something is ready to go?

**Comment by annalee** [comment]
It's a step someone on the team will do--we don't have separate testers.

**Comment by ccostino** [comment]
Ah gotcha, thanks for clarifying @annalee!

**Comment by ultrasaurus** [comment]
FWIW here's the Midas process:  https://github.com/18F/openopps-platform/blob/dev/CONTRIBUTING.md#reviewing-pull-requests

I believe getting stuff integrated quickly and doing the human testing on a shared dev server.  It is usually quick to submit a fix when issues are found, and we have rarely, if ever, had to back out a change.

**Comment by ccostino** [comment]
Awesome, thanks @ultrasaurus!  I agree, it's not good to let things get stale and sit for too long, but as noted in the review section you linked to, letting it sit for just a bit of time so folks actually have a chance to take a look is a good thing. :-)

**Comment by mtorres253** [comment]
Can this be moved to "needs review" or done? @ccostino

**Comment by ccostino** [comment]
If #36 looks good to folks and we're ready to merge those changes, then this can also be moved to done.

**Comment by ccostino** [comment]
#36 is now complete so I am going to mark this is as closed for us as well.  Thank you to everyone who contributed additional information and resources to their own team practices and external guides!  They were a big help for us and we appreciate the feedback. :-)
