### ISSUE TITLE
Research open source options for json -> form

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#45]
This is a task to research some of the options available to create a form to populate a json object (and then -> about.yml)

Some options: 
- [ ] http://schemaform.io/
- [ ] https://github.com/joshfire/jsonform
- [ ] https://www.mapbox.com/blog/team-directory-open-source/

**Comment by mtorres253** [comment]
Hi @jeremiak, can you update this story with your findings, or any other open source options you've explored?

**Comment by jeremiak** [comment]
Sure. Here is the current state of my research and what I still need to figure out:

The most popular tool online for this sort of thing (at least as measured by references in blogs) seems to be [`joshfire/jsonform`](https://github.com/joshfire/jsonform). The problem with this library is that the last updates were quite some time ago. The last commit was January 3, 2014. The problem that this poses is that the JSON schema spec has moved forward since then leaving some features such as `$ref` without support.

[SchemaForm](http://schemaform.io/) seems to work pretty well, based on some blog posts. It has been updated much more frequently and looks like its under mostly active development. I'm not sure which version of JSON Schema it supports, and the demo site breaks with our schema. My next step is to pull this tool town and see if I can get it up and running locally with about 30 minutes of effort.

Unfortunately, those look to be the only two real open source options that came up after some research.

**Comment by mtorres253** [comment]
Thanks @jeremiak

**Comment by jeremiak** [comment]
We're going to close this task out because we've decided to take a different route. Instead of building a generic JSON schema form builder, we're going to just include a smaller form in the live preview 18F/dashboard#302 to help folks fix errors on their `.about.yml` content.
