### ISSUE TITLE
Investigate project id

### ISSUE THREAD

**Issue by mtorres253** [18F/about_yml#52]
From today's dashboard demo meeting: We don't currently have a way to identify projects (other than the project name), this is brittle as it breaks when someone changes the name of their project, and there is no way to guarantee that the name is unique. This task is to think of an MVP for project identifiers that can help us attach data from a variety of sources to the correct project: about.yml, tock, anything else that might contain project data

Questions:
1. How do we guarantee uniqueness?
2. Where does it exist? about.yml? Team API?
3. How do we integrate with Tock?

Time-box to a 3 days. Whoever takes this is the lead person to work with the team and come up with some ideas.

Let's say the acceptance criteria is to come up with at least one idea for implementation.

Let's also consider the multi-repo situation and how we want to handle this.

**Comment by ccostino** [comment]
I'll take the lead on this since I have a suggestion - what if we were to use a GUID mechanism to generate IDs for projects?  This would prevent us from having to keep track of incrementing IDs for ourselves especially given the multi-repo situation yet allow us to maintain uniqueness.

An MVP could be as simple as one of us choosing our language of choice, leveraging the tools available for generating GUIDs of an acceptable length (5 characters, 8 characters?), and generating these IDs for folks.  As we generate an ID, we note the use of it and put it into a collection somewhere (dictionary/hash/what-have-you) paired with the project.  When it comes time to generate a new one, we could simply check if the GUID already exists by doing a key lookup and if it does, try again with another one until we get a unique one.

Thinking down the road, we could build a small tool (a la Fugacious) that provides a simple interface for folks to generate an unused GUID for themselves, their project, or whatever else is needed (I suppose mapping a `type` or `usage` attribute that is an enumeration of sorts would make sense at this point too).  This interface could then hook up to wherever we decide to house the single source of truth for these IDs and automatically save and update the information.  Given the progression of work lately, perhaps the data-private repo (or team-api.18f.gov repo in the future)?

Here are tools available for generating GUIDs in our languages of choice:
- Go:  _need reference_
- JavaScript:  [node-uuid](https://github.com/broofa/node-uuid)
- Python:  [UUID](https://docs.python.org/3/library/uuid.html)*
- Ruby:  [SecureRandom](http://ruby-doc.org/stdlib-2.2.3/libdoc/securerandom/rdoc/index.html)*

*Part of the language Standard Library.  You could also use the Linux shell if you're inclined:  [uuidgen](http://man7.org/linux/man-pages/man1/uuidgen.1.html)

The only thing I am unsure of is the Tock integration.  What exactly are we looking for regarding Tock?  Information from Tock to map to projects?  Information to give to Tock for projects?

I'm definitely curious to hear others' thoughts on this!  Good idea?  Bad idea?  The start of a bigger idea? :-)

**Comment by mbland** [comment]
cc: @philipashlock @jjediny

**Comment by JJediny** [comment]
See comment at #53

**Comment by ccostino** [comment]
Awesome, this could definitely help us in the future and I'm glad to see I'm not crazy in suggesting the GUID/UUID approach. :-)

I'm still curious about the Tock integration and what the expected outcome(s) of that is/are.  @mtorres253, are you able to give any additional insight into that?

**Comment by mtorres253** [comment]
Hey @ccostino. I'm thinking that the Tock integration could make available to Team API data about the cost of a particular project, when it began, who is working on it, time spent by whom, etc. Instead of us having to enter any of that in .about.yml. This would help some users of the dashboard (internal users who are interested in generating reports for GAO, for example)

**Comment by ccostino** [comment]
Ah, thanks @mtorres253!  So having a project ID that could be shared between the .about.yml files and Tock would be help make that integration possible is what you're going for?  Otherwise, I see the Tock integration as a separate issue/story.

In fact, it is probably separate anyway, just that this project ID link could tie the two things together (if it's possible to integrate the project ID into Tock somehow).

**Comment by mtorres253** [comment]
Hi, @ccostino yes, I agree that the Tock integration itself would be a separate thing. I was just trying to suggest some known integration points that we would have to think about in our analysis. So that is a separate problem. I really like the idea of a separate ID generation tool that doesn't depend on where we get the project information (.about.yml). It's a product and implementation thing. So the idea is that when a project is created in Team API, this is called to generate the unique ID. That way, it's not tied to .about.yml and the project data for setup can come from anywhere.

**Comment by ccostino** [comment]
@mtorres253: okay excellent, we are on the same wavelength!  And yes, the idea of a separate tool takes the ID generation out of any given repo so it could be used anywhere; in addition to (or instead of) a user interface we could also build an API that exposes a couple of interfaces to generate/register a new and unique ID.

**Comment by mbland** [comment]
Chatting with @ccostino, we're thinking it might be worth investigating Float as a GUID generator for projects.

**Comment by ccostino** [comment]
Link to Float features:  https://www.float.com/key-features/

**Comment by mtorres253** [comment]
Good idea @mbland @ccostino
